config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: "pages#home"

  resources :liked_artists
  resources :liked_albums
  resources :liked_songs
  
  resources :albums, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "albums#toggle_favorite"
    end
  end
  
  resources :songs, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "songs#toggle_favorite"
    end
  end
  
  resources :artists, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "artists#toggle_favorite"
    end
  end

end

app/models/album.rb
class Album < ApplicationRecord
# <<<<<<< HEAD
    has_one_attached :artwork
    
# =======
    acts_as_favoritable
# >>>>>>> submain
    belongs_to :artist
    has_many :songs

    #  def album_art
    #     return self.image
    #  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    acts_as_favoritable
    has_many :albums
    has_many :songs, through: :albums
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/liked_album.rb
class LikedAlbum < ApplicationRecord
  belongs_to :album
  belongs_to :user
end

app/models/liked_artist.rb
class LikedArtist < ApplicationRecord
  belongs_to :artist
  belongs_to :user
end

app/models/liked_song.rb
class LikedSong < ApplicationRecord
  belongs_to :song
  belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  acts_as_favoritable
  belongs_to :artist
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_favoritor

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
    has_many :liked_songs
    has_many :songs, through: :liked_songs
    
    has_many :liked_albums
    has_many :albums, through: :liked_albums
    
    has_many :liked_artists
    has_many :artists, through: :liked_artists 
    
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :find_album, only: [:show]
    before_action :authenticate_user!, only: :toggle_favorite
  
    def index 
        @albums = Albums.all
        @favorite_albums = current_user.favorited_by_type('Album')
    end

    def show
    end

    def toggle_favorite
        @album = Album.find(params[:id])
        current_user.favorited?(@album) ? current_user.unfavorite(@album) : current_user.favorite(@album)
    end
    
    private
    def find_album
        @album = Album.find(params[:id])
    end

    private
    def find_album
        @album = Album.find(params[:id])
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :find_artist, only: [:show]
    before_action :authenticate_user!, only: :toggle_favorite

    def index 
        @artists = Artist.all
    end

    def show
    end

    def toggle_favorite
        @artist = Artist.find(params[:id])
        current_user.favorited?(@artist) ? current_user.unfavorite(@artist) : current_user.favorite(@artist)
    end

    private
    def find_artist
        @artist = Artist.find(params[:id])
    end
        
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :find_song, only: [:show]
    before_action :authenticate_user!, only: :toggle_favorite

    def index 
        @songs = song.all
    end

    def show
    end

    def toggle_favorite
        @song = Song.find(params[:id])
        current_user.favorited?(@song) ? current_user.unfavorite(@song) : current_user.favorite(@song)
    end

    private
    def find_song
        @song = Song.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show]
    # before_action :authenticate_user!, only: 

    def show
    end

    def toggle_like
        @user.toggle(:liked_album).save
    end

    def username
        return self.email.split('@')[0].capitalize
    end

    private
    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/liked_albums_helper.rb
module LikedAlbumsHelper
end

app/helpers/liked_artists_helper.rb
module LikedArtistsHelper
end

app/helpers/liked_songs_helper.rb
module LikedSongsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/show.html.erb
<div id="head"><%= image_tag(@album.artwork, size: "100") %>
<h1> <%= @album.title %> </h1>
<% @user = current_user%>
<%= link_to "♥️", toggle_favorite_album_path(@album), remote: true, method: :post %>
</div>
<div id="link">
<%= link_to "Back to #{@album.artist.name}'s Albums", artist_path(@album.artist) %> <br>
<%= link_to 'Back to Profile', root_path %>
</div>
<table>
    <thead>
    <tr>
    <th> </th>
    <th>Song</th>
    <th>Artist</th>
    </tr>
    </thead>

    <tbody>
    <% @album.songs.each do |song| %>
        <tr>
            <td><%= link_to "♥️", toggle_favorite_song_path(song), remote: true, method: :post %> </td>
            <td><%= song.name.titleize %></td>
            <td><%= song.artist.name.titleize %></td>
        </tr>
    <%end%>
    </tbody>
</table>

app/views/albums/toggle_favorite.js.erb
var albumId = '<%= @album.id%>'
function toggleLikeButton(albumId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${albumId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(albumId);

app/views/artists/index.html.erb
<h1>Artists</h1>

<div id="link">
<%= link_to 'Back Profile', root_path %> <br>
</div>
<% @artists.order(:name).each do |artist| %>
<h3> <%= link_to artist.name, artist_path(artist) %> </h3>
<% end %>

app/views/artists/show.html.erb
<h1> <%= @artist.name %> </h1>

<div id="link">
    <%= link_to 'Back to Profile', root_path %> <span></span>
    <%= link_to "Back to Artists", artists_path(@artists) %>

    <% @user = current_user %>
</div>




<% @artist.albums.order(:release_date).reverse.each do |album| %>
    <%= link_to image_tag(album.artwork, size: "400"), album_path(album) %>

  
    <div id="albumtitle">
     <%=album.title%> <span></span>
     <%= link_to "♥️", toggle_favorite_album_path(album), remote: true, method: :post %>
    </div>

<% end %> 

app/views/artists/toggle_favorite.js.erb
var artistId = '<%= @artist.id%>'
function toggleLikeButton(artistId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${artistId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(artistId);

app/views/songs/toggle_favorite.js.erb
var songId = '<%= @song.id%>'

function toggleLikeButton(songId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${songId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(songId);